- hosts: 172.31.33.68
  become: True
  tasks:
    - name: install apache
      dnf:
        name: httpd
        state: present
    - name: copy index file on to apceh server
      copy:
        src: index.html
        dest: /var/www/html/
    - name: start and enable apache server
      service:
        name: httpd
        state: started
        enabled: True
