- hosts: 172.31.33.68
  become: True
  tasks:
    - name: install required packages
      dnf:
        name: "{{item}}"
        state: present
      with_items:
        - git
        - docker
        - maven
