- hosts: nginx
  become: True
  tasks:
    - name: install nignx server
      dnf:
        name: nginx
        state: present
    - name: start and enable
      service:
        name: nginx
        state: started
        enabled: True
    - name: copy config file
      template:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
      notify:
        - restart
  handlers:
    - name: restart
      service:
        name: nginx
        state: restarted
