- hosts: 172.31.33.68
  become: True
  tasks:
    - name: Install Java 17
      dnf:
        name: java-11-amazon-corretto-devel.x86_64
        state: present
    - name: Check tar file exists
      stat:
        path: /opt/apache-tomcat-9.0.80
      register: stat_result
    - name: Download tomat tar file
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.80/bin/apache-tomcat-9.0.80.tar.gz
        dest: /opt/
      when: not stat_result.stat.exists

    - name: extract tar file
      unarchive:
        src: /opt/apache-tomcat-9.0.80.tar.gz
        dest: /opt/
        remote_src: yes
      when: not stat_result.stat.exists
    - name: remore tomcat tar
      file:
        path: /opt/apache-tomcat-9.0.80.tar.gz
        state: absent
